---
operations:
  - install:
    - base
    - base-devel
    - linux
    - linux-firmware
    - grub
    - efibootmgr
    - i3-wm
    - i3status
    - dmenu
    - lightdm
    - lightdm-gtk-greeter
    - sudo
    - networkmanager
