---
instances:
- id:       welcome
  module:   welcome
  config:   welcome.conf
- id:       locale
  module:   locale
  config:   locale.conf
- id:       keyboard
  module:   keyboard
  config:   keyboard.conf
- id:       partition
  module:   partition
  config:   partition.conf
- id:       users
  module:   users
  config:   users.conf
- id:       summary
  module:   summary
  config:   summary.conf
- id:       unpackfs
  module:   unpackfs
  config:   unpackfs.conf
- id:       mount
  module:   mount
  config:   mount.conf
- id:       packages
  module:   packages
  config:   packages.conf
- id:       grubcfg
  module:   grubcfg
  config:   grubcfg.conf
- id:       bootloader
  module:   bootloader
  config:   bootloader.conf
- id:       networkcfg
  module:   networkcfg
- id:       fstab
  module:   fstab
- id:       machineid
  module:   machineid
- id:       locale-override
  module:   localecfg
- id:       keyboard-override
  module:   keyboardq
- id:       luksbootkeyfile
  module:   luksbootkeyfile
- id:       plymouthcfg
  module:   plymouthcfg
- id:       initramfscfg
  module:   initramfscfg
- id:       initramfs
  module:   initramfs
- id:       users-shell
  module:   users
  config:   users-shell.conf
- id:       removeuser
  module:   removeuser
- id:       finished
  module:   finished
  config:   finished.conf

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - networkcfg
    - users
    - users-shell
    - removeuser
    - fstab
    - locale-override
    - keyboard-override
    - luksbootkeyfile
    - plymouthcfg
    - initramfscfg
    - initramfs
    - packages
    - grubcfg
    - bootloader
    - machineid
    - finished

branding: arisos
prompt-install: true
dont-chroot: false
oops-mode: false
disable-cancel: false
disable-cancel-during-exec: false
preserve-files: []
